---

env:
  node: true
  jest: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 6
  sourceType: module

plugins:
  - jest
  - flowtype

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:flowtype/recommended'

rules:
  no-console: off
